### PR TITLE
Mention that auto-fetching stubs is unsupported

### PR DESCRIPTION
**Pull request by WhyNotHugo**

### CODE REVIEW

**Comment by asottile** [comment]
actually, can you change this to document that this is **not supported**. mutating pre-commit environments at runtime breaks the cache and can break parallel runs

**Comment by WhyNotHugo** [comment]
Good thing I bought it up, now I know.

I'll update the PR to reflect that.

**Comment by WhyNotHugo** [comment]
Is there any way to install dependencies from a file (e.g.: `typing-requirements.txt`) or from an `extras`? I'd prefer avoiding having to duplicate them inside the pre-commit definitions.

**Review by asottile — APPROVED** [review]

**Pull request merged**
